### ISSUE TITLE
老师，很喜欢你的swift课程，来一门iOS开发实战课？

### ISSUE THREAD

**Issue by kimmy-wang** [liuyubobobo/liuyubobobo#1]

**Comment by liuyubobobo** [comment]
谢谢你的支持啦。iOS 实战课程短期内应该不会出了。一方面是 iOS 就业整体不够景气，导致需求不大；另一方面因为 iOS native SDK 每年都会变动，导致课程维护成本过大。🥺

**Comment by kimmy-wang** [comment]
极客时间上的iOS课程卖了将近3000份

**Comment by liuyubobobo** [comment]
他们算法课卖了多少份？

**Comment by kimmy-wang** [comment]
> 他们算法课卖了多少份？

有一门数据结构与算法之美的课程卖了86000多份，不过价格也便宜，团购价69块钱，单买99
